name: Backend CI

on:
  push:
    paths:
    - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log into Docker Hub
      run: echo $DOCKER_TOKEN | docker login  --username duxet --password-stdin
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build backend --tag strimoid/strm:${{ github.sha }}
    - name: Push the Docker image
      run: docker push strimoid/strm:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Kubernetes credentials
      run: mkdir $HOME/.kube; echo $K8S_CONFIG | base64 -d > $HOME/.kube/config
      env:
        K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
    - name: Upgrade Kubernetes deployment
      run: kubectl set image deployment/strm strm=strimoid/strm:${{ github.sha }}
